version: '3.5'

services:
  postgres:
    container_name: postgres_c
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/postgres
    volumes:
      - postgres_c:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres_c:
